name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SPACE_APP_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
      SPACE_APP_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
      SPACE_APP_API_KEY: ${{ secrets.API_KEY }}

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Create keystore
      id: release_cert
      uses: timheuer/base64-to-file@v1.0.3
      with:
        fileName: 'space_release.jks'
        encodedString: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
    - name: Lint
      run: ./gradlew lint
    - name: Build with Gradle
      env:
        SPACE_APP_KEYSTORE_PATH: ${{ steps.release_cert.outputs.filePath }}
      run: ./gradlew testDebugUnitTest assembleDebug
    - name: Publish apk artefact
      uses: actions/upload-artifact@v1
      with:
        name: app-debug
        path: app/build/outputs/apk
#    TODO I: how merge unit test results. Note: "apply plugin: 'android-reporting'" works just for instrumented tests
#    - name: Publish test results artefact
#      uses: actions/upload-artifact@v1
#      with:
#        name: test-results-debug
#        path: app/build/reports/tests
#        if: failure()